### ISSUE TITLE
5V-tolerant FPGA?

### ISSUE THREAD

**Issue by sorgelig** [daglem/reDIP-SID#10]
Hi!

in readme you wrote: 
```
All FPGA I/O is 5V tolerant, and can drive 5V TTL.
```
If it is true then why board uses level shifter?

**Comment by daglem** [comment]
The FPGA I/O is only available on the pin headers, and there it is 5V tolerant, because of the level shifter.

The FPGA in itself is not 5V tolerant.

**Comment by sorgelig** [comment]
May be it's worth to modify readme to `All board I/O is 5V tolerant` instead `FPGA`
