### ISSUE TITLE
Can't find the ICE chip in the market

### ISSUE THREAD

**Issue by hexad** [daglem/reDIP-SID#4]
There are literally 0 IC of this in the market, in order to build this.
Is this possible that the whole thing works with another FPGA chip that you can find in the market?

Perhaps one from the same product line?

**Comment by daglem** [comment]
The availability of the iCE40UP5K FPGA is actually quite good, compared to other FPGAs in the market.
E.g. 25 000 are expected at Mouser in December.
I am not going to redesign the board for any other FPGA, as long as there are no superior options.

**Comment by hexad** [comment]
Thanks for the Mouser tip! And for the excellent project!
